language: node_js
node_js:
  - '0.10'
  - '0.11'
before_script:
  - npm install -g grunt-cli <% if(filters.fullstack) { %>bower<% if (filters.sass) { %>
  - gem install sass<% } %>
  - bower install<% } %>
services: mongodb